from lxml import html
import requests
f = open('data.csv','w')
paths=['https://www.primeabgb.com/online-price-reviews-india/asus-rog-geforce-gtx-1070-ti-strix-gtx1070ti-8g-gaming-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-geforce-gtx-1070-ti-strix-gtx1070ti-a8g-gaming-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1050-ti-exoc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1070-ti-ex-snpr-white-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-aorus-geforce-gtx-1080-ti-11g-11gb-graphic-card-gv-n108taorus-11gd/',
'https://www.primeabgb.com/online-price-reviews-india/inno3d-ichill-geforce-gtx-1070-ti-x3-edition-graphic-card-c107t3-1sdn-p5dn/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gt-1030-2g-lp-oc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1050-2g-ocv1-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1050-2gt-ocv1-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1050-ti-4g-ocv1-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1050-ti-4gt-ocv1-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1050-ti-gaming-x-4g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1060-3gt-ocv2-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1060-6gt-ocv2-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1070-aero-itx-8g-oc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1080-armor-8g-oc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1080-gaming-x-8g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1080-ti-armor-11g-oc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1080-ti-gaming-x-11g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-gt-710-2gd5-lp-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-radeon-rx-560-aero-itx-4g-oc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-radeon-rx-580-gaming-x-8g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-radeon-rx-460-oc-4gb-graphic-card-11257-11-41g/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1070-ti-ex-8gb-gddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1070-oc-mini-8gb-gddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-aorus-geforce-gtx-1060-xtreme-edition-6g-graphic-card-gv-n1060aorus-x-6gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1060-windforce-oc-6g-graphic-card-gv-n1060wf2oc-6gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1070-ti-gaming-8g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-radeon-rx-580-gv-rx580gaming-8gd-8gb-atx-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1070-ti-aero-8g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1070-ti-armor-8g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1070-ti-gaming-8g-graphics-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1080-ti-gaming-x-trio-11gb-gddr5x-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-radeon-rx-vega-56-8g-graphics-card/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-radeon-rx-470-4gd5-mining-graphic-card-11256-35-10g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-radeon-rx-vega-56-8g-graphics-card-21276-00-20g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-rx-vega-64-8gb-hbm2-graphic-card-21275-02-20g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-rx-vega-64-8gb-hbm2-limited-edition-graphic-card-21275-01-20g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-rx-vega-64-8gb-hbm2-liquid-cooling-graphic-card-21275-00-40g/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1070-8gb-gddr5-graphic-card-zt-p10700f-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1070-ti-8gb-amp-edition-graphic-card-zt-p10710b-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1070-ti-8gb-amp-extreme-graphic-card-zt-p10710b-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1070-ti-8gb-mini-graphic-card-zt-p10710g-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-ti-mini-11gb-graphic-card-zt-p10810g-10p/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-pulse-radeon-rx-560-4gd5-graphic-card-11267-01-41g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-graphics-card-radeon-rx-550-4gb-gddr5-oc-pulse-11268-01-41g/',
'https://www.primeabgb.com/online-price-reviews-india/asus-dual-rx580-o8g-rx-580-8gb-gddr5-oc-edition-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-dual-rx580-o4g-rx-580-4gb-gddr5-oc-edition-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-gtx-1050-ti-4gb-gddr5-phoenix-fan-edition-graphic-card-ph-gtx1050ti-4g/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-strix-gtx1050ti-4g-gaming-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-pulse-amd-radeon-rx-580-8g-gddr5-graphic-card-11265-05-20g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-pulse-radeon-rx-580-8gb-gddr5-oc-ati-pci-e-graphic-card-11265-05-41g/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-aorus-radeon-rx570-4g-graphic-card-gv-rx570aorus-4gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-radeon-rx-570-gv-rx570gaming-4gd-4gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/powercolor-red-devil-radeon-rx-580-8gb-gddr5-graphic-card-axrx-580-8gbd5-3dhoc/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-nitro-radeon-rx-570-8gb-gddr5-graphics-card-11266-09-41g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-nitro-radeon-rx-580-4gb-gddr5-graphic-card-11265-07-41g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-nitro-radeon-rx-580-8gb-gddr5-oc-ati-pci-e-graphic-card-11265-01-41g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-nitro-radeon-rx-580-8gd5-graphics-card-11265-01-20g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-radeon-rx-550-2gb-gddr5-oc-pulse-11268-03-41g-graphics-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-strix-rx570-04g-gaming-oc-edition-4gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rx550-2g-rx-550-2gb-gddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-radeon-rx-570-4gb-gddr5-ex-rx570-4g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-strix-rx570-4g-gaming-rx-570-4gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-strix-rx580-o8g-gaming-rx-580-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-pulse-radeon-rx-570-4gd5-graphic-card-11266-04-41g/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-nitro-radeon-rx-570-4gd5-graphic-card-11266-14-41g/',
'https://www.primeabgb.com/online-price-reviews-india/asus-nvidia-geforce-gtx-1050ti-ex-gtx1050ti-4g-4-gb-gddr5/',
'https://www.primeabgb.com/online-price-reviews-india/asus-geforce-gtx-1060-6gb-strix-oc-strix-gtx1060-dc2o6g-video-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-strix-gtx-1080-ti-oc-rog-strix-gtx1080ti-o11g-gaming-11gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/asus-rog-strix-gtx1080ti-11g-gaming-1080ti-11gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-ti-blower-graphic-card-zt-p10810b-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-ti-amp-edition-graphic-card-zt-p10810d-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-ti-amp-extreme-core-11gb-graphic-card-zt-p10810f-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-ti-amp-extreme-graphic-card-zt-p10810c-10p/',
'https://www.primeabgb.com/online-price-reviews-india/asus-geforce-gtx-1080-ti-11gb-founders-edition-graphic-card-gtx1080ti-fe/',
'https://www.primeabgb.com/online-price-reviews-india/inno3d-nvidia-gtx-1080-ti-11gb-founders-edition-graphic-card-n108t-1ddn-q6mo/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1080-ti-11gb-gv-n108td5x-b-founders-edition-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-ti-founders-edition-11gb-gddr5x-graphic-card-zt-p10810a-10p/',
'https://www.primeabgb.com/online-price-reviews-india/asus-gtx-1070-8gb-graphic-card-rog-rog-strix-gtx1070-o8g-gaming/',
'https://www.primeabgb.com/online-price-reviews-india/msi-gtx-1060-armor-3g-ocv1-3gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-gtx-1070-armor-8g-oc-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1080-xtreme-gaming-water-cooling-8g-graphic-card-gv-n1080xtreme-w-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-aorus-geforce-gtx-1080-xtreme-edition-8g-graphic-card-gv-n1080aorus-x-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1080-xtreme-gaming-premium-pack-8g-graphic-card-gv-n1080wf3oc-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1080-windforce-oc-8g-graphic-card-gv-n1080wf3oc-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1070-windforce-8gb-graphic-card-gv-n1070wf2-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1070-8gb-mini-graphic-card-gv-n1070ixoc-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1060-xtreme-gaming-6g-graphic-card-gv-n1060xtreme-6gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1060-windforce-graphic-card-gv-n1060d5-6gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1060-6gb-mini-graphic-card-gv-n1060ixoc-6gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1060-g1-gaming-graphic-card-gv-n1060ixoc-3gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1050-ti-g1-gaming-graphic-card-gv-n105tg1-gaming-4gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1050-ti-oc-4g-graphic-card-gv-n105toc-4gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1050-g1-gaming-2g-graphic-card-gv-n1050g1-gaming-2gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1050-oc-2g-graphic-card-gv-n1050oc-2gd/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-1080-mini-8gb-graphic-card-zt-p10800h-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1060-3gb-amp-edition-graphic-card-zt-p10610e-10m/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1070-exoc-snpr-black-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gt-1030-exoc-white-2gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1050-oc-2gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1050-ti-oc-4gb-ddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1060-oc-3gb-graphic-card-2/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1060-oc-6gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1070-katana-8gb-gddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1080-ti-exoc-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1050-oc-2gb-ddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/inno3d-gtx-1050-ti-compact-gddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/inno3d-gtx-1050-ti-twin-x2-gddr5-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1050-ti-mini-4gb-graphic-card-zt-p10510a-10l/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1050-ti-oc-edition-graphic-card-zt-p10510b-10l/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1050-mini-2gb-graphic-card-zt-p10500a-10l/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1080-ex-oc-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1080-hof-8gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1060-ex-oc-6gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/sapphire-radeon-rx-460-2g-d5-graphic-card-11257-00-41g/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1070-mini-8gb-graphic-card-zt-p10700g-10m/',
'https://www.primeabgb.com/online-price-reviews-india/sahpphire-nitro-radeon-rx-470-8-gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/msi-gtx-1060-armor-6g-oc-edition-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1060-mini-3gb-super-compact-graphics-card-zt-p10610a-10l/',
'https://www.primeabgb.com/online-price-reviews-india/rx-480-iceq-x%c2%b2-roaring-oc-8gb-graphic-card-hs-480r8dcbr/',
'https://www.primeabgb.com/online-price-reviews-india/asus-gtx-1070-8gb-graphic-card-rog-strix-gtx1070-8g-gaming/',
'https://www.primeabgb.com/online-price-reviews-india/msi-gtx-1060-gaming-x-6g-6gb-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1060-g1-gaming-6g-6gb-graphic-card-gv-n1060g1-gaming-6gd/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1070-xtreme-gaming-graphic-card-gv-n1070xtreme-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/asus-gtx-1080-8gb-turbo-graphic-card-turbo-gtx1080-8g/',
'https://www.primeabgb.com/online-price-reviews-india/asus-gtx-1060-6gb-graphic-card-rog-strix-gtx1060-6g-gaming/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1060-amp-edition-graphic-card-zt-p10600b-10m/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1060-mini-graphic-card-zt-p10600a-10l/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-gtx-1070-g1-gaming-graphic-card-gv-n1070g1-gaming-8gd/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1070-amp-extreme-graphic-card-zt-p10700b-10p/',
'https://www.primeabgb.com/online-price-reviews-india/galax-geforce-gtx-1070-virtual-edition-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1070-amp-edition-graphic-card-zt-p10700c-10p/',
'https://www.primeabgb.com/online-price-reviews-india/msi-geforce-gtx-1070-gaming-x-8g-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/gigabyte-geforce-gtx-1080-g1-gaming-gv-n1080g1-gaming-8gd-video-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-gtx-1080-amp-extreme-graphic-card-zt-p10800b-10p/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-nvidia-geforce-pascal-gtx-1080-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/zotac-geforce-gtx-750-ti-zt-70601-10m-graphic-card/',
'https://www.primeabgb.com/online-price-reviews-india/evga-geforce-gt-730-2gb-graphic-card-02g-p3-1733-kr/']
for page in paths:
    page = requests.get(page,verify=False)
    tree = html.fromstring(page.content)
    price = tree.xpath('//div[@itemprop="offers"]/meta[@itemprop="price"]/@content')
    avail = tree.xpath('//div[@itemprop="offers"]/link[@itemprop="availability"]/@href')
    #name = tree.xpath('//div[@itemprop="description"]/p/text()')
    name = tree.xpath('//h1[@class="title"]/text()')
    print ('Name: ',name[0])
    print ('Price: ',price[0])
    print ('Availability: ',avail[0][19:])
    data = str(name[0]),str(price[0]),str(avail[0][19:])
    f.write(str(data))
    f.write("\n")

f.close()
